package configinspect

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"localclash/internal/configmeta"

	"gopkg.in/yaml.v3"
)

type Options struct {
	ConfigPath string
	Limit      int
}

type BaseResult struct {
	Config     string      `json:"config"`
	Layer      string      `json:"layer"`
	Modifiable bool        `json:"modifiable"`
	Summary    BaseSummary `json:"summary"`
	Note       string      `json:"note"`
}

type BaseSummary struct {
	Mode               string                `json:"mode"`
	ExternalController string                `json:"external_controller,omitempty"`
	ExternalUI         string                `json:"external_ui,omitempty"`
	ProxiesCount       int                   `json:"proxies_count"`
	ProxyGroups        []ProxyGroupSummary   `json:"proxy_groups"`
	RuleProviders      []RuleProviderSummary `json:"rule_providers"`
	RulesCount         int                   `json:"rules_count"`
	RulesSample        []string              `json:"rules_sample"`
}

type ProxyGroupSummary struct {
	Name         string `json:"name"`
	Type         string `json:"type"`
	ProxiesCount int    `json:"proxies_count"`
}

type RuleProviderSummary struct {
	Name     string `json:"name"`
	Behavior string `json:"behavior"`
	Type     string `json:"type"`
}

type OverlayResult struct {
	Config          string                            `json:"config"`
	Layer           string                            `json:"layer"`
	Modifiable      bool                              `json:"modifiable"`
	MetadataPresent bool                              `json:"metadata_present"`
	OverlayPresent  bool                              `json:"overlay_present"`
	Packs           []configmeta.OverlayPack          `json:"packs"`
	VirtualTargets  []configmeta.OverlayVirtualTarget `json:"virtual_targets"`
	RuleProviders   []configmeta.OverlayRuleProvider  `json:"rule_providers"`
	Rules           []configmeta.OverlayRule          `json:"rules"`
	Insertion       string                            `json:"insertion,omitempty"`
}

func InspectBase(opts Options) (BaseResult, error) {
	path := defaultConfigPath(opts.ConfigPath)
	limit := normalizedLimit(opts.Limit)
	config, err := readConfigMap(path)
	if err != nil {
		return BaseResult{}, err
	}
	metadata, metadataPresent, err := readMetadata(config)
	if err != nil {
		return BaseResult{}, err
	}
	overlayProviderNames := map[string]bool{}
	overlayProxyGroupNames := map[string]bool{}
	overlayRuleLines := map[string]bool{}
	if metadataPresent {
		for _, provider := range metadata.Overlay.RuleProviders {
			overlayProviderNames[provider.Name] = true
		}
		for _, target := range metadata.Overlay.VirtualTargets {
			overlayProxyGroupNames[target.ID] = true
		}
		for _, rule := range metadata.Overlay.Rules {
			overlayRuleLines[formatOverlayRule(rule)] = true
		}
	}
	rules := filterStrings(stringSlice(config["rules"]), overlayRuleLines)
	return BaseResult{
		Config:     path,
		Layer:      "base",
		Modifiable: false,
		Summary: BaseSummary{
			Mode:               stringFromMap(config, "mode"),
			ExternalController: stringFromMap(config, "external-controller"),
			ExternalUI:         stringFromMap(config, "external-ui"),
			ProxiesCount:       len(anySlice(config["proxies"])),
			ProxyGroups:        limitProxyGroups(filterProxyGroups(summarizeProxyGroups(config["proxy-groups"]), overlayProxyGroupNames), limit),
			RuleProviders:      limitRuleProviders(filterRuleProviders(summarizeRuleProviders(config["rule-providers"]), overlayProviderNames), limit),
			RulesCount:         len(rules),
			RulesSample:        limitStrings(rules, limit),
		},
		Note: "Base config is generated by localClash and is not modified through MCP plan tools.",
	}, nil
}

func InspectOverlay(opts Options) (OverlayResult, error) {
	path := defaultConfigPath(opts.ConfigPath)
	limit := normalizedLimit(opts.Limit)
	config, err := readConfigMap(path)
	if err != nil {
		return OverlayResult{}, err
	}
	result := OverlayResult{
		Config:         path,
		Layer:          "overlay",
		Modifiable:     true,
		Packs:          []configmeta.OverlayPack{},
		VirtualTargets: []configmeta.OverlayVirtualTarget{},
		RuleProviders:  []configmeta.OverlayRuleProvider{},
		Rules:          []configmeta.OverlayRule{},
	}
	metadata, ok, err := readMetadata(config)
	if err != nil {
		return OverlayResult{}, err
	}
	if !ok {
		return result, nil
	}
	result.MetadataPresent = true
	result.Packs = limitOverlayPacks(metadata.Overlay.Packs, limit)
	result.VirtualTargets = limitOverlayVirtualTargets(metadata.Overlay.VirtualTargets, limit)
	result.RuleProviders = limitOverlayRuleProviders(metadata.Overlay.RuleProviders, limit)
	result.Rules = limitOverlayRules(metadata.Overlay.Rules, limit)
	result.Insertion = metadata.Overlay.Insertion
	result.OverlayPresent = len(metadata.Overlay.Packs) > 0 ||
		len(metadata.Overlay.VirtualTargets) > 0 ||
		len(metadata.Overlay.RuleProviders) > 0 ||
		len(metadata.Overlay.Rules) > 0
	return result, nil
}

func readMetadata(config map[string]any) (configmeta.Metadata, bool, error) {
	raw, ok := config[configmeta.Key]
	if !ok {
		return configmeta.Metadata{}, false, nil
	}
	var metadata configmeta.Metadata
	data, err := yaml.Marshal(raw)
	if err != nil {
		return configmeta.Metadata{}, false, err
	}
	if err := yaml.Unmarshal(data, &metadata); err != nil {
		return configmeta.Metadata{}, false, err
	}
	return metadata, true, nil
}

func readConfigMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("config %q does not exist; run config_render first", path)
		}
		return nil, err
	}
	var config map[string]any
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, err
	}
	return config, nil
}

func defaultConfigPath(path string) string {
	if strings.TrimSpace(path) == "" {
		return "generated/mihomo.yaml"
	}
	return path
}

func normalizedLimit(limit int) int {
	if limit <= 0 {
		return 20
	}
	return limit
}

func summarizeProxyGroups(value any) []ProxyGroupSummary {
	var out []ProxyGroupSummary
	for _, raw := range anySlice(value) {
		group, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		out = append(out, ProxyGroupSummary{
			Name:         stringFromMap(group, "name"),
			Type:         stringFromMap(group, "type"),
			ProxiesCount: len(anySlice(group["proxies"])),
		})
	}
	return out
}

func summarizeRuleProviders(value any) []RuleProviderSummary {
	providers, ok := value.(map[string]any)
	if !ok {
		return nil
	}
	names := make([]string, 0, len(providers))
	for name := range providers {
		names = append(names, name)
	}
	sort.Strings(names)
	out := make([]RuleProviderSummary, 0, len(names))
	for _, name := range names {
		provider, _ := providers[name].(map[string]any)
		out = append(out, RuleProviderSummary{
			Name:     name,
			Behavior: stringFromMap(provider, "behavior"),
			Type:     stringFromMap(provider, "type"),
		})
	}
	return out
}

func filterProxyGroups(values []ProxyGroupSummary, excluded map[string]bool) []ProxyGroupSummary {
	if len(excluded) == 0 {
		return values
	}
	out := make([]ProxyGroupSummary, 0, len(values))
	for _, value := range values {
		if !excluded[value.Name] {
			out = append(out, value)
		}
	}
	return out
}

func filterRuleProviders(values []RuleProviderSummary, excluded map[string]bool) []RuleProviderSummary {
	if len(excluded) == 0 {
		return values
	}
	out := make([]RuleProviderSummary, 0, len(values))
	for _, value := range values {
		if !excluded[value.Name] {
			out = append(out, value)
		}
	}
	return out
}

func filterStrings(values []string, excluded map[string]bool) []string {
	if len(excluded) == 0 {
		return values
	}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if !excluded[value] {
			out = append(out, value)
		}
	}
	return out
}

func formatOverlayRule(rule configmeta.OverlayRule) string {
	if rule.Type == "" || rule.Provider == "" || rule.Target == "" {
		return ""
	}
	return rule.Type + "," + rule.Provider + "," + rule.Target
}

func anySlice(value any) []any {
	if values, ok := value.([]any); ok {
		return values
	}
	return nil
}

func stringSlice(value any) []string {
	var out []string
	for _, item := range anySlice(value) {
		if text, ok := item.(string); ok {
			out = append(out, text)
		}
	}
	return out
}

func stringFromMap(values map[string]any, key string) string {
	if values == nil {
		return ""
	}
	if text, ok := values[key].(string); ok {
		return text
	}
	return ""
}

func limitProxyGroups(values []ProxyGroupSummary, limit int) []ProxyGroupSummary {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]ProxyGroupSummary{}, values...)
}

func limitRuleProviders(values []RuleProviderSummary, limit int) []RuleProviderSummary {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]RuleProviderSummary{}, values...)
}

func limitStrings(values []string, limit int) []string {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]string{}, values...)
}

func limitOverlayPacks(values []configmeta.OverlayPack, limit int) []configmeta.OverlayPack {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]configmeta.OverlayPack{}, values...)
}

func limitOverlayVirtualTargets(values []configmeta.OverlayVirtualTarget, limit int) []configmeta.OverlayVirtualTarget {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]configmeta.OverlayVirtualTarget{}, values...)
}

func limitOverlayRuleProviders(values []configmeta.OverlayRuleProvider, limit int) []configmeta.OverlayRuleProvider {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]configmeta.OverlayRuleProvider{}, values...)
}

func limitOverlayRules(values []configmeta.OverlayRule, limit int) []configmeta.OverlayRule {
	if len(values) > limit {
		values = values[:limit]
	}
	return append([]configmeta.OverlayRule{}, values...)
}
